[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "The Future of Entertainment: How Artificial Intelligence and Other Technologies Will Change the Way We Consume Media"
